export const topCreators = [
	{
		displayName: "Alice",
		username: "alice",
		walletAddress: "0xAb12Fe983457Ac05",
		views: 3541,
		likes: 1024,
		yourSponsorships: 5,
		totalSponsorships: 56,
		totalEarnings: 102.43,
		yourEarnings: 12.4,
	},
	{
		displayName: "Bob",
		username: "bob",
		walletAddress: "0xCd34Re783654Ft09",
		views: 6894,
		likes: 784,
		yourSponsorships: 2,
		totalSponsorships: 78,
		totalEarnings: 89.3,
		yourEarnings: 9.2,
	},
	{
		displayName: "Charlie",
		username: "charlie",
		walletAddress: "0xEf56De893147Bv07",
		views: 7023,
		likes: 832,
		yourSponsorships: 6,
		totalSponsorships: 67,
		totalEarnings: 94.5,
		yourEarnings: 14.3,
	},
	{
		displayName: "Dave",
		username: "dave",
		walletAddress: "0xGh78Fe982341Nc01",
		views: 4398,
		likes: 492,
		yourSponsorships: 4,
		totalSponsorships: 43,
		totalEarnings: 43.8,
		yourEarnings: 8.1,
	},
	{
		displayName: "Eve",
		username: "eve",
		walletAddress: "0xIj90Ge785674Pt02",
		views: 5623,
		likes: 622,
		yourSponsorships: 3,
		totalSponsorships: 59,
		totalEarnings: 64.9,
		yourEarnings: 9.7,
	},
	{
		displayName: "Frank",
		username: "frank",
		walletAddress: "0xKl12He983209Vw03",
		views: 7891,
		likes: 1042,
		yourSponsorships: 8,
		totalSponsorships: 110,
		totalEarnings: 132.6,
		yourEarnings: 17.3,
	},
	{
		displayName: "Grace",
		username: "grace",
		walletAddress: "0xMn34Ie783256Xy04",
		views: 6253,
		likes: 688,
		yourSponsorships: 4,
		totalSponsorships: 70,
		totalEarnings: 72.3,
		yourEarnings: 10.2,
	},
	{
		displayName: "Heidi",
		username: "heidi",
		walletAddress: "0xOp56Je782934Za05",
		views: 3489,
		likes: 394,
		yourSponsorships: 2,
		totalSponsorships: 36,
		totalEarnings: 37.2,
		yourEarnings: 7.4,
	},
	{
		displayName: "Ivan",
		username: "ivan",
		walletAddress: "0xQr78Ke980273Qe06",
		views: 8962,
		likes: 1123,
		yourSponsorships: 9,
		totalSponsorships: 120,
		totalEarnings: 143.5,
		yourEarnings: 19.1,
	},
	{
		displayName: "Judy",
		username: "judy",
		walletAddress: "0xSt90Le786120Wa07",
		views: 6231,
		likes: 689,
		yourSponsorships: 3,
		totalSponsorships: 72,
		totalEarnings: 71.4,
		yourEarnings: 9.8,
	},
];

export const pendingSponsorships = [
	{
		creator: {
			displayName: "Alice",
			username: "alice",
			walletAddress: "0xAb12Fe983457Ac05",
			views: 3541,
		},
		sponsorship: {
			title: "Aquaphor",
			description: "Description...",
			cost: 2.5,
			numOfVideos: 5,
			trigger: "views",
			sponsorURL: "https://example.com/WALDO",
			script: "Lorem ipsum...",
			currency: "USDC",
			walletAddress: "0xAb12Fe983457Ac05",
		},
	},
	{
		creator: {
			displayName: "John",
			username: "john",
			walletAddress: "0xAb12Fe983457Ac05",
			views: 2186,
		},
		sponsorship: {
			title: "Aquaphor",
			description: "Description...",
			cost: 1.7,
			numOfVideos: 2,
			trigger: "likes",
			sponsorURL: "https://example.com/WALDO",
			script: "Lorem ipsum...",
			currency: "USDC",
			walletAddress: "0xAb12Fe983457Ac05",
		},
	},
];

export const completedSponsorships = [
	{
		creator: {
			displayName: "Mary",
			username: "mary",
			walletAddress: "0xAb12Fe983457Ac05",
			views: 4422,
		},
		sponsorship: {
			title: "Cabals Labs Brand Ambassadorships",
			description: "Description...",
			cost: 1.0,
			currency: "USDC",
			numOfVideos: 4,
			trigger: "views",
			sponsorURL: "https://example.com/WALDO",
			script: "Lorem ipsum...",
			walletAddress: "0xAb12Fe983457Ac05",
		},
	},
	{
		creator: {
			displayName: "Paul",
			username: "paul",
			walletAddress: "0xAb12Fe983457Ac05",
			views: 7475,
		},
		sponsorship: {
			title: "Aquaphor",
			description: "Description...",
			cost: 1.3,
			currency: "USDC",
			numOfVideos: 1,
			trigger: "likes",
			sponsorURL: "https://example.com/WALDO",
			script: "Lorem ipsum...",
			walletAddress: "0xAb12Fe983457Ac05",
		},
	},
];

export const topSponsors = [
	{
		displayName: "Raid Shadow Legends",
		walletAddress: "0xAb12Fe983457Ac05",
		yourSponsorships: 5,
		totalSponsorships: 56,
		totalEarnings: 102.43,
		yourEarnings: 12.4,
	},
	{
		displayName: "Better Help",
		walletAddress: "0xCd34Re783654Ft09",
		yourSponsorships: 2,
		totalSponsorships: 78,
		totalEarnings: 89.3,
		yourEarnings: 9.2,
	},
];

export const currentListings = [
	{
		title: "Cabals Labs Brand Ambassadorships",
		description: "Description...",
		cost: 1.2,
		trigger: "views",
		sponsorURL: "https://caballabs.com",
		script: "Stuff...",
		currency: "ETH",
		walletAddress: "0xCd34Re783654Ft09",
	},
	{
		title: "Aquaphor",
		description: "Description...",
		cost: 40,
		trigger: "views",
		sponsorURL: "https://caballabs.com",
		script: "Stuff...",
		currency: "USDC",
		walletAddress: "0xAb12Fe983457Ac05",
	},
];
